### PR TITLE
Update spandsp.rb to 0d2e6ac65e0e8f53d652665a743015a88bf048d4

### PR DESCRIPTION
**Pull request by andywolk**

### CODE REVIEW

**Review by mjerris — APPROVED** [review]

**Comment by MarioG-X** [comment]
This results in an error:
mario@Marios-Mac-mini ~ % brew install signalwire/homebrew-signalwire/spandsp
==> Downloading https://formulae.brew.sh/api/formula.jws.json
##################################################################################################################################### 100.0%
==> Fetching signalwire/signalwire/spandsp
==> Downloading https://github.com/freeswitch/spandsp/archive/0d2e6ac65e0e8f53d652665a743015a88bf048d4.tar.gz
==> Downloading from https://codeload.github.com/freeswitch/spandsp/tar.gz/0d2e6ac65e0e8f53d652665a743015a88bf048d4
    #-=O#-    #      #                                                                                                                     
==> Installing spandsp from signalwire/signalwire
==> ./configure --with-pic
Last 15 lines from /Users/mario/Library/Logs/Homebrew/spandsp/01.configure:
2024-01-11 00:11:27 +0000

./configure
--disable-dependency-tracking
--prefix=/usr/local/Cellar/spandsp/4
--with-pic


If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/signalwire/homebrew-signalwire/issues

**Comment by MarioG-X** [comment]
01.configure file log referenced above is:
[01.configure.txt](https://github.com/signalwire/homebrew-signalwire/files/13895849/01.configure.txt)

**Comment by MarioG-X** [comment]
OK, I assume that means wait on it until merged. I will try again when completed. Thank you!

**Comment by andywolk** [comment]
@MarioG-X you can try now.

**Comment by MarioG-X** [comment]
Hmm, exact same messages, looks to be downloading version ending in "d4" (I erased HB cache before doing this):
mario@Marios-Mac-mini ~ % brew install signalwire/homebrew-signalwire/spandsp
==> Fetching signalwire/signalwire/spandsp
==> Downloading https://github.com/freeswitch/spandsp/archive/0d2e6ac65e0e8f53d652665a743015a88bf048d4.tar.gz
==> Downloading from https://codeload.github.com/freeswitch/spandsp/tar.gz/0d2e6ac65e0e8f53d652665a743015a88bf048d4
  # -=#=-  #      #                                                                                                                        
==> Installing spandsp from signalwire/signalwire
==> ./configure --with-pic
Last 15 lines from /Users/mario/Library/Logs/Homebrew/spandsp/01.configure:
2024-01-11 00:47:25 +0000

./configure
--disable-dependency-tracking
--prefix=/usr/local/Cellar/spandsp/4
--with-pic


If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/signalwire/homebrew-signalwire/issues

**Comment by andywolk** [comment]
Seems not updated. The link should be `https://files.freeswitch.org/downloads/libs/spandsp-3.0.0-0d2e6ac65e.tar.gz` and not `https://github.com/freeswitch/spandsp/archive/0d2e6ac65e0e8f53d652665a743015a88bf048d4.tar.gz`

**Comment by MarioG-X** [comment]
Should I stand by?

**Comment by andywolk** [comment]
No. Try `brew update` and then retry.

**Comment by MarioG-X** [comment]
AHA, that did it! Now installed. Testing build now.

**Comment by MarioG-X** [comment]
FS Master completes and comes up! Back in business. Thank you!

**Pull request merged**
